"""empty message

Revision ID: 347403b13620
Revises: 3c72f52bda2e
Create Date: 2021-11-19 17:09:17.642548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347403b13620'
down_revision = '3c72f52bda2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('categories', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('postalCode', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('websites', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lojas')
    # ### end Alembic commands ###
